# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: argis.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='argis.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0b\x61rgis.proto\"\xca\x05\n\x02TT\x12\x15\n\x03ins\x18\x02 \x01(\x0b\x32\x08.TT.Info\x1a\xac\x05\n\x04Info\x12\x1d\n\x06\x64sfsdd\x18\x01 \x01(\x0b\x32\r.TT.Info.data\x1a\x84\x05\n\x04\x64\x61ta\x12\x10\n\x08ObjectId\x18\x01 \x01(\x05\x12 \n\x02\x64\x61\x18\x02 \x01(\x0b\x32\x14.TT.Info.data.datain\x12\x1d\n\x02\x61\x61\x18\x08 \x01(\x0b\x32\x11.TT.Info.data.din\x12\n\n\x02\x62\x62\x18\t \x01(\x05\x12!\n\x04\x64\x66\x66n\x18\x0c \x01(\x0b\x32\x13.TT.Info.data.asdda\x12\x1e\n\x01t\x18\r \x03(\x0b\x32\x13.TT.Info.data.title\x12!\n\x01\x64\x18\x0f \x03(\x0b\x32\x16.TT.Info.data.datareal\x1a*\n\x06\x64\x61tain\x12\x0f\n\x07oidname\x18\x01 \x01(\t\x12\x0f\n\x07oiddata\x18\x02 \x01(\x05\x1a#\n\x03\x64in\x12\x0b\n\x03kkd\x18\x01 \x01(\t\x12\x0f\n\x07oiddata\x18\x02 \x01(\x05\x1a\xa0\x01\n\x05\x61sdda\x12%\n\x03\x66\x66\x66\x18\x02 \x01(\x0b\x32\x18.TT.Info.data.asdda.fsdf\x12*\n\x03sda\x18\x03 \x01(\x0b\x32\x1d.TT.Info.data.asdda.fsffggddf\x1a\x1e\n\x04\x66sdf\x12\n\n\x02xx\x18\x01 \x01(\t\x12\n\n\x02sd\x18\x02 \x01(\t\x1a$\n\tfsffggddf\x12\x0b\n\x03vdf\x18\x01 \x01(\t\x12\n\n\x02gf\x18\x02 \x01(\t\x1a\x34\n\x05title\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04\x63ode\x18\x02 \x01(\x05\x12\x0f\n\x07namerep\x18\x03 \x01(\t\x1a\x8c\x01\n\x08\x64\x61tareal\x12&\n\x01r\x18\x01 \x03(\x0b\x32\x1b.TT.Info.data.datareal.real\x1aX\n\x04real\x12\r\n\x05value\x18\x01 \x01(\t\x12\x10\n\x08postcode\x18\x04 \x01(\x05\x12\x0f\n\x07hexdata\x18\x03 \x01(\t\x12\x10\n\x08longdata\x18\x08 \x01(\x05\x12\x0c\n\x04oifd\x18\x05 \x01(\x05\x62\x06proto3'
)




_TT_INFO_DATA_DATAIN = _descriptor.Descriptor(
  name='datain',
  full_name='TT.Info.data.datain',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='oidname', full_name='TT.Info.data.datain.oidname', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='oiddata', full_name='TT.Info.data.datain.oiddata', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=291,
  serialized_end=333,
)

_TT_INFO_DATA_DIN = _descriptor.Descriptor(
  name='din',
  full_name='TT.Info.data.din',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='kkd', full_name='TT.Info.data.din.kkd', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='oiddata', full_name='TT.Info.data.din.oiddata', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=335,
  serialized_end=370,
)

_TT_INFO_DATA_ASDDA_FSDF = _descriptor.Descriptor(
  name='fsdf',
  full_name='TT.Info.data.asdda.fsdf',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='xx', full_name='TT.Info.data.asdda.fsdf.xx', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sd', full_name='TT.Info.data.asdda.fsdf.sd', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=465,
  serialized_end=495,
)

_TT_INFO_DATA_ASDDA_FSFFGGDDF = _descriptor.Descriptor(
  name='fsffggddf',
  full_name='TT.Info.data.asdda.fsffggddf',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='vdf', full_name='TT.Info.data.asdda.fsffggddf.vdf', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='gf', full_name='TT.Info.data.asdda.fsffggddf.gf', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=497,
  serialized_end=533,
)

_TT_INFO_DATA_ASDDA = _descriptor.Descriptor(
  name='asdda',
  full_name='TT.Info.data.asdda',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='fff', full_name='TT.Info.data.asdda.fff', index=0,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sda', full_name='TT.Info.data.asdda.sda', index=1,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_TT_INFO_DATA_ASDDA_FSDF, _TT_INFO_DATA_ASDDA_FSFFGGDDF, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=373,
  serialized_end=533,
)

_TT_INFO_DATA_TITLE = _descriptor.Descriptor(
  name='title',
  full_name='TT.Info.data.title',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='TT.Info.data.title.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='code', full_name='TT.Info.data.title.code', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='namerep', full_name='TT.Info.data.title.namerep', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=535,
  serialized_end=587,
)

_TT_INFO_DATA_DATAREAL_REAL = _descriptor.Descriptor(
  name='real',
  full_name='TT.Info.data.datareal.real',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='TT.Info.data.datareal.real.value', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='postcode', full_name='TT.Info.data.datareal.real.postcode', index=1,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='hexdata', full_name='TT.Info.data.datareal.real.hexdata', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='longdata', full_name='TT.Info.data.datareal.real.longdata', index=3,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='oifd', full_name='TT.Info.data.datareal.real.oifd', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=642,
  serialized_end=730,
)

_TT_INFO_DATA_DATAREAL = _descriptor.Descriptor(
  name='datareal',
  full_name='TT.Info.data.datareal',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='r', full_name='TT.Info.data.datareal.r', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_TT_INFO_DATA_DATAREAL_REAL, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=590,
  serialized_end=730,
)

_TT_INFO_DATA = _descriptor.Descriptor(
  name='data',
  full_name='TT.Info.data',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ObjectId', full_name='TT.Info.data.ObjectId', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='da', full_name='TT.Info.data.da', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='aa', full_name='TT.Info.data.aa', index=2,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bb', full_name='TT.Info.data.bb', index=3,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dffn', full_name='TT.Info.data.dffn', index=4,
      number=12, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='t', full_name='TT.Info.data.t', index=5,
      number=13, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='d', full_name='TT.Info.data.d', index=6,
      number=15, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_TT_INFO_DATA_DATAIN, _TT_INFO_DATA_DIN, _TT_INFO_DATA_ASDDA, _TT_INFO_DATA_TITLE, _TT_INFO_DATA_DATAREAL, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=86,
  serialized_end=730,
)

_TT_INFO = _descriptor.Descriptor(
  name='Info',
  full_name='TT.Info',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='dsfsdd', full_name='TT.Info.dsfsdd', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_TT_INFO_DATA, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=730,
)

_TT = _descriptor.Descriptor(
  name='TT',
  full_name='TT',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ins', full_name='TT.ins', index=0,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_TT_INFO, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=730,
)

_TT_INFO_DATA_DATAIN.containing_type = _TT_INFO_DATA
_TT_INFO_DATA_DIN.containing_type = _TT_INFO_DATA
_TT_INFO_DATA_ASDDA_FSDF.containing_type = _TT_INFO_DATA_ASDDA
_TT_INFO_DATA_ASDDA_FSFFGGDDF.containing_type = _TT_INFO_DATA_ASDDA
_TT_INFO_DATA_ASDDA.fields_by_name['fff'].message_type = _TT_INFO_DATA_ASDDA_FSDF
_TT_INFO_DATA_ASDDA.fields_by_name['sda'].message_type = _TT_INFO_DATA_ASDDA_FSFFGGDDF
_TT_INFO_DATA_ASDDA.containing_type = _TT_INFO_DATA
_TT_INFO_DATA_TITLE.containing_type = _TT_INFO_DATA
_TT_INFO_DATA_DATAREAL_REAL.containing_type = _TT_INFO_DATA_DATAREAL
_TT_INFO_DATA_DATAREAL.fields_by_name['r'].message_type = _TT_INFO_DATA_DATAREAL_REAL
_TT_INFO_DATA_DATAREAL.containing_type = _TT_INFO_DATA
_TT_INFO_DATA.fields_by_name['da'].message_type = _TT_INFO_DATA_DATAIN
_TT_INFO_DATA.fields_by_name['aa'].message_type = _TT_INFO_DATA_DIN
_TT_INFO_DATA.fields_by_name['dffn'].message_type = _TT_INFO_DATA_ASDDA
_TT_INFO_DATA.fields_by_name['t'].message_type = _TT_INFO_DATA_TITLE
_TT_INFO_DATA.fields_by_name['d'].message_type = _TT_INFO_DATA_DATAREAL
_TT_INFO_DATA.containing_type = _TT_INFO
_TT_INFO.fields_by_name['dsfsdd'].message_type = _TT_INFO_DATA
_TT_INFO.containing_type = _TT
_TT.fields_by_name['ins'].message_type = _TT_INFO
DESCRIPTOR.message_types_by_name['TT'] = _TT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TT = _reflection.GeneratedProtocolMessageType('TT', (_message.Message,), {

  'Info' : _reflection.GeneratedProtocolMessageType('Info', (_message.Message,), {

    'data' : _reflection.GeneratedProtocolMessageType('data', (_message.Message,), {

      'datain' : _reflection.GeneratedProtocolMessageType('datain', (_message.Message,), {
        'DESCRIPTOR' : _TT_INFO_DATA_DATAIN,
        '__module__' : 'argis_pb2'
        # @@protoc_insertion_point(class_scope:TT.Info.data.datain)
        })
      ,

      'din' : _reflection.GeneratedProtocolMessageType('din', (_message.Message,), {
        'DESCRIPTOR' : _TT_INFO_DATA_DIN,
        '__module__' : 'argis_pb2'
        # @@protoc_insertion_point(class_scope:TT.Info.data.din)
        })
      ,

      'asdda' : _reflection.GeneratedProtocolMessageType('asdda', (_message.Message,), {

        'fsdf' : _reflection.GeneratedProtocolMessageType('fsdf', (_message.Message,), {
          'DESCRIPTOR' : _TT_INFO_DATA_ASDDA_FSDF,
          '__module__' : 'argis_pb2'
          # @@protoc_insertion_point(class_scope:TT.Info.data.asdda.fsdf)
          })
        ,

        'fsffggddf' : _reflection.GeneratedProtocolMessageType('fsffggddf', (_message.Message,), {
          'DESCRIPTOR' : _TT_INFO_DATA_ASDDA_FSFFGGDDF,
          '__module__' : 'argis_pb2'
          # @@protoc_insertion_point(class_scope:TT.Info.data.asdda.fsffggddf)
          })
        ,
        'DESCRIPTOR' : _TT_INFO_DATA_ASDDA,
        '__module__' : 'argis_pb2'
        # @@protoc_insertion_point(class_scope:TT.Info.data.asdda)
        })
      ,

      'title' : _reflection.GeneratedProtocolMessageType('title', (_message.Message,), {
        'DESCRIPTOR' : _TT_INFO_DATA_TITLE,
        '__module__' : 'argis_pb2'
        # @@protoc_insertion_point(class_scope:TT.Info.data.title)
        })
      ,

      'datareal' : _reflection.GeneratedProtocolMessageType('datareal', (_message.Message,), {

        'real' : _reflection.GeneratedProtocolMessageType('real', (_message.Message,), {
          'DESCRIPTOR' : _TT_INFO_DATA_DATAREAL_REAL,
          '__module__' : 'argis_pb2'
          # @@protoc_insertion_point(class_scope:TT.Info.data.datareal.real)
          })
        ,
        'DESCRIPTOR' : _TT_INFO_DATA_DATAREAL,
        '__module__' : 'argis_pb2'
        # @@protoc_insertion_point(class_scope:TT.Info.data.datareal)
        })
      ,
      'DESCRIPTOR' : _TT_INFO_DATA,
      '__module__' : 'argis_pb2'
      # @@protoc_insertion_point(class_scope:TT.Info.data)
      })
    ,
    'DESCRIPTOR' : _TT_INFO,
    '__module__' : 'argis_pb2'
    # @@protoc_insertion_point(class_scope:TT.Info)
    })
  ,
  'DESCRIPTOR' : _TT,
  '__module__' : 'argis_pb2'
  # @@protoc_insertion_point(class_scope:TT)
  })
_sym_db.RegisterMessage(TT)
_sym_db.RegisterMessage(TT.Info)
_sym_db.RegisterMessage(TT.Info.data)
_sym_db.RegisterMessage(TT.Info.data.datain)
_sym_db.RegisterMessage(TT.Info.data.din)
_sym_db.RegisterMessage(TT.Info.data.asdda)
_sym_db.RegisterMessage(TT.Info.data.asdda.fsdf)
_sym_db.RegisterMessage(TT.Info.data.asdda.fsffggddf)
_sym_db.RegisterMessage(TT.Info.data.title)
_sym_db.RegisterMessage(TT.Info.data.datareal)
_sym_db.RegisterMessage(TT.Info.data.datareal.real)


# @@protoc_insertion_point(module_scope)
